### ISSUE TITLE
Display doesn't clear upon reset

### ISSUE THREAD

**Issue by jmk** [modulolabs/modulo-python#1]
The display module (possibly due to outdated firmware?) doesn't clear to black when it's reset. This means that when I terminate a script and run a new one, the last image displayed remains on the screen.

This might not be noticeable if the script that's run draws something new to the display, but I started by writing a trivial program that cleared the screen to black, and was confused when nothing happened.

The Display object's internal buffer has been cleared to all zeroes, so it considers this a no-op when calling update(), and the image isn't cleared. An easy workaround in the meantime is to call Display.clear(1) to set all pixels white, update the display, then proceed as usual.

**Comment by pixelpixi** [comment]
This should be fixed in the released version. Please let me know if not.
